<a href="https://colab.research.google.com/github/nishesh21/pythonProject/blob/main/self_Performance_metrics_Instructions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Compute performance metrics for the given Y and Y_score without sklearn

In [ ]:
#1st case, (for 5_a.csv data)
#computing confusion matrix
import numpy as np
import pandas as pd
df1=pd.read_csv("5_a.csv")
#ypred is basically the predictions made by model
df1['ypred']=np.where(df1['proba']>=0.5,1,0)


yactual=df1['y'].to_numpy().astype(int)
ypredicted=df1['ypred'].to_numpy()
print(yactual)
print(ypredicted)

#reference took from https://stackoverflow.com/questions/2148543/how-to-write-a-confusion-matrix-in-python
def confusion_matrix(actual_y,predicted_y):
  conf_mat=np.zeros((2,2))#here we have only 2 classes
  for i,j in zip(actual_y,predicted_y):#here i am just using a zip function to create pairs
    conf_mat[i][j] += 1 # lets say i=1 and j=1, then this will add 1 to that position, initially conf_mat[1][1]=0, then 1 ia added so conf_mat[1][1]=1 and so on.
  return conf_mat


[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]


In [ ]:
#function run(confusion_matrix)
a=confusion_matrix(yactual,ypredicted)
print(a)



[[    0.   100.]
 [    0. 10000.]]


In [ ]:
#2. computing f1 score, f1 score is defined by 2*P*R/P+R(P IS PRECISION AND R IS RECALL)(for 5_a.csv)

import pandas as pd
import numpy as np
from tqdm import tqdm
df1=pd.read_csv("5_a.csv")
df1['ypred']=np.where(df1['proba']>=0.5,1,0)


def F1_score(data):
  Tp=((data['y']==1) & (data['ypred']==1)).sum()
  Tn=((data['y']==0) & (data['ypred']==0)).sum()
  Fp=((data['y']==0) & (data['ypred']==1)).sum()
  Fn=((data['y']==1) & (data['ypred']==0)).sum()
 
  
  Precision=Tp/(Tp+Fp)
  Recall=Tp/(Tp+Fn)
  F1=2*Precision*Recall/(Precision+Recall)

  return F1
  
  



In [ ]:
#function run(F1_score)
F1_score(df1)

0.9950248756218906

In [ ]:
#3. calculating  Auc_score (for 5_a.csv)

import pandas as pd
import numpy as np
from tqdm import tqdm
df1=pd.read_csv("5_a.csv")
for i in df1['proba']:
  if i>=0.5:
    df1['ypred']=1
  else:
    df1['ypred']=0
df1=df1.sort_values(by=['proba'],ascending=False)


def auc_s(data):
  tpr=[]
  fpr=[]
  for threshold in tqdm(data['proba'].unique()):

    data['ythreshold']=np.where(data['proba']>=threshold,1,0)
    Tp=((data['y']==1) & (data['ythreshold']==1)).sum()
    Tn=((data['y']==0) & (data['ythreshold']==0)).sum()
    Fp=((data['y']==0) & (data['ythreshold']==1)).sum()
    Fn=((data['y']==1) & (data['ythreshold']==0)).sum()
    true_positive_rate=Tp/(Tp+Fn)
    tpr.append(true_positive_rate)
    
    false_positive_rate=Fp/(Tn+Fp)
    fpr.append(false_positive_rate)


  print("length of tpr is",len(tpr))
  print("length of fpr is ",len(fpr))
  auc_score=np.trapz(tpr,fpr)
  print(auc_score)

  return auc_score





In [ ]:
#function run(auc_score)
auc_s(df1)

100%|██████████| 10100/10100 [00:48<00:00, 208.15it/s]

length of tpr is 10100
length of fpr is  10100
0.48829900000000004


0.48829900000000004

In [ ]:
#4. computing accuracy score
import pandas as pd
import numpy as np
from tqdm import tqdm
df1=pd.read_csv("5_a.csv")
for i in df1['proba']:
  if i>=0.5:
    df1['ypred']=1
  else:
    df1['ypred']=0

def accuracy_score(data):
  Tp=((data['y']==1) & (data['ypred']==1)).sum()
  Tn=((data['y']==0) & (data['ypred']==0)).sum()
  Fp=((data['y']==0) & (data['ypred']==1)).sum()
  Fn=((data['y']==1) & (data['ypred']==0)).sum()
 

  accuracy= (Tp+Tn)/(Tp+Tn+Fp+Fn)

  return accuracy


In [ ]:
#function run(accuracy_score)
accuracy_score(df1)


0.9900990099009901

In [ ]:
#TASK2 
#confusion matrix(for 5_b.csv)
import numpy as np
import pandas as pd
df2=pd.read_csv("5_b.csv")
#ypred is basically the predictions made by model
df2['ypred']=np.where(df2['proba']>=0.5,1,0)

yactual=df2['y'].to_numpy().astype(int)
ypredicted=df2['ypred'].to_numpy()
print(yactual)
print(ypredicted)

#reference took from https://stackoverflow.com/questions/2148543/how-to-write-a-confusion-matrix-in-python
def confusion_matrix1(actual_y,predicted_y):
  conf_mat=np.zeros((2,2))#here we have only 2 classes
  for i,j in zip(actual_y,predicted_y):#here i am just using a zip function to create pairs
    conf_mat[i][j] += 1 # lets say i=1 and j=1, then this will add 1 to that position, initially conf_mat[1][1]=0, then 1 ia added so conf_mat[1][1]=1 and so on.
  return conf_mat



[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [ ]:
#function run(confusion_matrix)(for 5_b matrix)
b=confusion_matrix1(yactual,ypredicted)
print(b)

[[9761.  239.]
 [  45.   55.]]


In [ ]:
#2. computing f1 score, f1 score is defined by 2*P*R/P+R(P IS PRECISION AND R IS RECALL)(for 5_b.csv)

import pandas as pd
import numpy as np
from tqdm import tqdm
df2=pd.read_csv("5_b.csv")
df2['ypred']=np.where(df2['proba']>=0.5,1,0)


def F1_score(data):
  Tp=((data['y']==1) & (data['ypred']==1)).sum()
  Tn=((data['y']==0) & (data['ypred']==0)).sum()
  Fp=((data['y']==0) & (data['ypred']==1)).sum()
  Fn=((data['y']==1) & (data['ypred']==0)).sum()
 
  
  Precision=Tp/(Tp+Fp)
  Recall=Tp/(Tp+Fn)
  F1=2*Precision*Recall/(Precision+Recall)

  return F1
  
  




In [ ]:
#function run(F1_score)
F1_score(df2)

0.2791878172588833

In [ ]:
#3. calculating  Auc_score (for 5_b.csv)

import pandas as pd
import numpy as np
from tqdm import tqdm
df2=pd.read_csv("5_b.csv")
df2=df2.sort_values(by=['proba'],ascending=False)


def auc_s(data):
  tpr=[]
  fpr=[]
  for threshold in tqdm(data['proba'].unique()):

    data['ythreshold']=np.where(data['proba']>=threshold,1,0)
    Tp=((data['y']==1) & (data['ythreshold']==1)).sum()
    Tn=((data['y']==0) & (data['ythreshold']==0)).sum()
    Fp=((data['y']==0) & (data['ythreshold']==1)).sum()
    Fn=((data['y']==1) & (data['ythreshold']==0)).sum()
    true_positive_rate=Tp/(Tp+Fn)
    tpr.append(true_positive_rate)
    
    false_positive_rate=Fp/(Tn+Fp)
    fpr.append(false_positive_rate)


  print("length of tpr is",len(tpr))
  print("length of fpr is ",len(fpr))
  auc_score=np.trapz(tpr,fpr)
  print(auc_score)

  return auc_score





In [ ]:
result=auc_s(df2)

100%|██████████| 10100/10100 [00:47<00:00, 213.92it/s]

length of tpr is 10100
length of fpr is  10100
0.9377570000000001


In [ ]:
#4. computing accuracy score
import pandas as pd
import numpy as np
from tqdm import tqdm
df2=pd.read_csv("5_b.csv")
df2['ypred']=np.where(df2['proba']>=0.5,1,0)


def accuracy_score(data):
  Tp=((data['y']==1) & (data['ypred']==1)).sum()
  Tn=((data['y']==0) & (data['ypred']==0)).sum()
  Fp=((data['y']==0) & (data['ypred']==1)).sum()
  Fn=((data['y']==1) & (data['ypred']==0)).sum()
 

  accuracy= (Tp+Tn)/(Tp+Tn+Fp+Fn)

  return accuracy


In [ ]:
#function run(accuracy_score)
accuracy_score(df2)

0.9718811881188119

In [21]:
#psudo dataframe to check things
da=pd.DataFrame(data=data1)
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
yavg=(sum(y_true))/len(y_true)
print(yavg)
squares=[]
for i in y_true:
  squares.append(np.square((i-yavg)))
sstotal=sum(squares)

error=[]
for i,j in zip(y_true,y_pred):
  error.append(np.square((i-j)))
ssresidual=sum(error)

rsquare=1-(ssresidual/sstotal)
print(rsquare)

2.875
0.9486081370449679


In [19]:
from sklearn.metrics import r2_score
r2_score(y_true,y_pred)

0.9486081370449679

<font color='red'><b>C.</b></font> Compute the best threshold (similarly to ROC curve computation) of probability which gives lowest values of metric <b>A</b> for the given data <strong>5_c.csv</strong>
<br>

you will be predicting label of a data points like this: $y^{pred}= \text{[0 if y_score < threshold  else 1]}$

$ A = 500 \times \text{number of false negative} + 100 \times \text{numebr of false positive}$

<pre>
   <b>Note 1:</b> in this data you can see number of negative points > number of positive points
   <b>Note 2:</b> use pandas or numpy to read the data from <b>5_c.csv</b>
</pre>

In [9]:
#Task3
from tqdm import tqdm
import numpy as np
import pandas as pd
df3=pd.read_csv("5_c.csv")
df3.head()

def best_score(data):
  metric={}
  for threshold in tqdm(data['prob'].unique()):

    data['ythreshold']=np.where(data['prob']<threshold,0,1)
    Fp=((data['y']==0) & (data['ythreshold']==1)).sum()
    Fn=((data['y']==1) & (data['ythreshold']==0)).sum()
    A=500*Fn+100*Fp
    metric[threshold]=A

  Minimum_threshold=min(metric,key=metric.get)
  return Minimum_threshold


  
    



In [11]:
best_score(df3)


100%|██████████| 2791/2791 [00:04<00:00, 591.39it/s]


0.2300390278970873

In [ ]:
#TASK4

# 1. MEAN SQUARE ERROR

import numpy as np
import pandas as pd
df4=pd.read_csv("5_d.csv")
def mean_square_error(data):
  yactuall=data['y'].to_numpy().astype(int)
  ypredd=data['pred'].to_numpy()
  squares=[]
  for i,j in zip(yactuall,ypredd):
    squares.append(np.square((i-j)))
  mean_square=sum(squares)/len(squares)
  return (mean_square)
    

In [ ]:
mean_square_error(df4)



177.16569974554707

In [4]:
#2. MAPE(Mean absolute percentage error)
#so because actual values can be zero, we have to take modified mape
#modified mape= summation of all the absolute error/summation of all the actual values
import numpy as np
import pandas as pd
df4=pd.read_csv("5_d.csv")
def mape(data):
  yactuall=data['y'].to_numpy().astype(int)
  ypredd=data['pred'].to_numpy()
  error=[]
  for i,j in zip(yactuall,ypredd):
    error.append(abs((i-j)))
  modified_mape=sum(error)/sum(yactuall)
  print(modified_mape)

In [5]:
mape(df4)

0.1291202994009687


In [24]:
#3.R^2 ERROR
import numpy as np
import pandas as pd
df4=pd.read_csv("5_d.csv")

def rsquare(data):
  yactuall=data['y'].to_numpy().astype(int)
  ypredd=data['pred'].to_numpy()
  yavg=(sum(yactuall))/len(yactuall)
  squares=[]
  for i in yactuall:
    squares.append(np.square((i-yavg)))
  sstotal=sum(squares)

  error=[]
  for i,j in zip(yactuall,ypredd):
    error.append(np.square((i-j)))
  ssresidual=sum(error)

  rsquare=1-(ssresidual/sstotal)

  return rsquare






In [25]:
rsquare(df4)

0.9563582786990964